In [1]:
import pandas as pd
import numpy as np

In [2]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [3]:
frame3 = pd.DataFrame(pop)
frame3

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [4]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [5]:
pdata = {'Ohio': frame3['Ohio'][:-1],
'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [6]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [7]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [8]:
arr2d = [[1, 2, 3],[4, 5, 6]]

df = pd.DataFrame(
    data=arr2d,
    columns=["C1", "C2", "C3"],
    index=["R1", "R2"]
)

print(df)

    C1  C2  C3
R1   1   2   3
R2   4   5   6

In [9]:
dict1 = {'A':[1, 2, 3],
         'B':[4, 5, 6]}

df = pd.DataFrame(data=dict1)
df

   A  B
0  1  4
1  2  5
2  3  6

In [10]:
dataseries = {'A':pd.Series([1,2], index= ['x','y']),'B':pd.Series([3,4], index= ['y','z'])}
df = pd.DataFrame(data=dataseries)
df

     A    B
x  1.0  NaN
y  2.0  3.0
z  NaN  4.0

In [11]:
data = [{'A':1,'B':2},{'C':3,'D':4}]
df = pd.DataFrame(data)
df

     A    B    C    D
0  1.0  2.0  NaN  NaN
1  NaN  NaN  3.0  4.0

In [12]:
obj = pd.Series(range(3), index=['a','b','c'])
index = obj.index
print(index)
index[1:]
# index[1]='d' #type error

Index(['a', 'b', 'c'], dtype='object')

Index(['b', 'c'], dtype='object')

In [13]:
labels = pd.Index(np.arange(3))
labels

Index([0, 1, 2], dtype='int64')

In [14]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [15]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [16]:
d1 = pd.Index([1,2,3,4,5])
d2 = pd.Index([5,6])
d3 = pd.Index([1,2,3])

In [17]:
print(d1.append(d2))
print(d1.difference(d3))
print(d1.intersection(d3))
print(d1.union(d2))
print(d1.isin([2,3]))
print(d1.delete(1))
print(d1.drop(3))
print(d1.insert(loc=5, item=6))
print(d1.is_monotonic_increasing)
print(d1.is_monotonic_decreasing)
print(d1.is_unique)
print(d1.unique())

Index([1, 2, 3, 4, 5, 5, 6], dtype='int64')
Index([4, 5], dtype='int64')
Index([1, 2, 3], dtype='int64')
Index([1, 2, 3, 4, 5, 6], dtype='int64')
[False  True  True False False]
Index([1, 3, 4, 5], dtype='int64')
Index([1, 2, 4, 5], dtype='int64')
Index([1, 2, 3, 4, 5, 6], dtype='int64')
True
False
True
Index([1, 2, 3, 4, 5], dtype='int64')

In [18]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
print(obj)
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
print(obj2)

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64
a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [19]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [20]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3.reindex(range(6), method='bfill')

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

In [88]:
obj4 = pd.DataFrame(np.arange(9).reshape(3,3), index=['a','b','c'],columns=['Ohio','Texas','California'])
print(obj4)
obj5 = obj4.reindex(['a','b','c','d'],fill_value=2)
print(obj5)
states = ['Ohio','Utah','California']
obj6 = obj4.reindex(columns=states)     #old column data removes column data entirely and add empty new column
print(obj6)
f1 = obj4.drop(['Ohio'],axis=1)
print(f1)
f1 = obj4.drop(['a'])
print(f1)

print(obj4.loc[obj4['Texas'] > 1, ['Ohio', 'Texas']])

   Ohio  Texas  California
a     0      1           2
b     3      4           5
c     6      7           8
   Ohio  Texas  California
a     0      1           2
b     3      4           5
c     6      7           8
d     2      2           2
   Ohio  Utah  California
a     0   NaN           2
b     3   NaN           5
c     6   NaN           8
   Texas  California
a      1           2
b      4           5
c      7           8
   Ohio  Texas  California
b     3      4           5
c     6      7           8
   Ohio  Texas
b     3      4
c     6      7

In [22]:
s=pd.Series([10,20,30], index=['a','b','c'])
print(s)
s1 = s.reindex(['a','b','c','d'], method='ffill')
print(s1)
s2 = s.reindex(['a','b','c','d'], fill_value=1)
print(s2)
s3 = s.reindex(['a','b','c','d','e','f'], method='ffill', limit=2)
print(s3)

s4 = pd.Series([0,1,2], index=[10,20,30])
s5 = s4.reindex([11,21,32], method='nearest',tolerance=2)
print(s5)

a    10
b    20
c    30
dtype: int64
a    10
b    20
c    30
d    30
dtype: int64
a    10
b    20
c    30
d     1
dtype: int64
a    10.0
b    20.0
c    30.0
d    30.0
e    30.0
f     NaN
dtype: float64
11    0
21    1
32    2
dtype: int64

In [30]:
mindx = pd.MultiIndex.from_product([['a','b','c'],[1,2]])
mindx
mindx1 = pd.MultiIndex.from_product([['A','B'],[1,2]])
s = pd.Series([10,20,30,40],index=mindx1)
s
s1 = s.reindex(s1)
s1

a  1   NaN
   2   NaN
b  1   NaN
   2   NaN
c  1   NaN
   2   NaN
dtype: float64