In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.Series(np.random.randn(9), index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'],[1, 2, 3, 1, 3, 1, 2, 2, 3]])

In [3]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [8]:
data

a  1   -0.324958
   2   -2.904931
   3   -1.436261
b  1    1.822135
   3   -0.186973
c  1    0.434019
   2    0.017095
d  2    0.767209
   3    0.782856
dtype: float64

In [4]:
data['b']

1    1.822135
3   -0.186973
dtype: float64

In [5]:
data['b':'c']

b  1    1.822135
   3   -0.186973
c  1    0.434019
   2    0.017095
dtype: float64

In [ ]:
data.loc[['b', 'd']]

b  1    1.822135
   3   -0.186973
d  2    0.767209
   3    0.782856
dtype: float64

In [7]:
data.loc[:, 2]

a   -2.904931
c    0.017095
d    0.767209
dtype: float64

In [9]:
data.unstack()

          1         2         3
a -0.324958 -2.904931 -1.436261
b  1.822135       NaN -0.186973
c  0.434019  0.017095       NaN
d       NaN  0.767209  0.782856

In [14]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
columns=[['Ohio', 'Ohio', 'Colorado'],
['Green', 'Red', 'Green']])
frame

     Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [15]:
frame.index.names = ['key1', 'key2']

In [26]:
frame.swaplevel('key1', 'key2')
frame.columns.names = ['state', 'color']

In [ ]:
frame.sort_index(level=1)

           Ohio     Colorado
          Green Red    Green
key1 key2
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [18]:
frame.swaplevel(0, 1).sort_index(level=0)

           Ohio     Colorado
          Green Red    Green
key2 key1
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

In [ ]:
frame.groupby('key2').sum()

      Ohio     Colorado
     Green Red    Green
key2
1        6   8       10
2       12  14       16

In [27]:
frame.groupby('color', axis=1).sum()

/var/folders/f5/r_4n8c2j2qs88z3chgyzp6h00000gn/T/ipykernel_98703/3387249451.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  frame.groupby('color', axis=1).sum()

color      Green  Red
key1 key2
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

In [29]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],'data1': range(7)})
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],'data2': range(3)})
print(df1)
print(df2)

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6
  key  data2
0   a      0
1   b      1
2   d      2

In [ ]:
pd.merge(df1, df2)

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [31]:
pd.merge(df1, df2, on='key')

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [34]:
df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],'data1': range(7)})
df4 = pd.DataFrame({'rkey': ['a', 'b', 'd'], 'data2': range(3)})
print(df3)
print(df4)

  lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6
  rkey  data2
0    a      0
1    b      1
2    d      2

In [35]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey')

  lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    a      2    a      0
3    a      4    a      0
4    a      5    a      0
5    b      6    b      1

In [36]:
pd.merge(df1, df2, how='outer')

  key  data1  data2
0   a    2.0    0.0
1   a    4.0    0.0
2   a    5.0    0.0
3   b    0.0    1.0
4   b    1.0    1.0
5   b    6.0    1.0
6   c    3.0    NaN
7   d    NaN    2.0

In [37]:
pd.merge(df1, df2, how='left')

  key  data1  data2
0   b      0    1.0
1   b      1    1.0
2   a      2    0.0
3   c      3    NaN
4   a      4    0.0
5   a      5    0.0
6   b      6    1.0

In [38]:
pd.merge(df1, df2, how='right')

  key  data1  data2
0   a    2.0      0
1   a    4.0      0
2   a    5.0      0
3   b    0.0      1
4   b    1.0      1
5   b    6.0      1
6   d    NaN      2